### ISSUE TITLE
Can we use this to store and recall on demand instead of on change?

### ISSUE THREAD

**Issue by muzicman82** [MatKlucznyk/JsonStore#5]
Hi,

I've been using this module to store data as it is, but I'm considering a use case where I'd have several instances for system presets. Instead of the code writing changes as the signal values change, I'd like to have to pulse a "store" to write the current values and "recall" to recall the stored values. 

Might this be an easy S+ code change?

**Comment by MatKlucznyk** [comment]
Take a look at my latest commit, I think it will do what you want
